const Data = {
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 60,
      countInStock: 20,
      brand: " Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Best Pants",
      category: "Pants",
      image: "/images/p1.jpg",
      price: 70,
      countInStock: 0,
      brand: " Nike",
      rating: 1.6,
      numReviews: 8,
      description: "a grate product!",
    },
    {
      _id: "3",
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/d3.jpg",
      price: 50,
      countInStock: 15,
      brand: " Nike",
      rating: 4.2,
      numReviews: 5,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Best Pants",
      category: "Pants",
      image: "/images/p2.jpg",
      price: 70,
      countInStock: 30,
      brand: " Nike",
      rating: 4.5,
      numReviews: 8,
      description: "a grate product!",
    },
    {
      _id: "5",
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/d2.jpg",
      price: 50,
      countInStock: 0,
      brand: " Nike",
      rating: 3.2,
      numReviews: 5,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Best Pants",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 70,
      countInStock: 10,
      brand: " Nike",
      rating: 2.5,
      numReviews: 8,
      description: "a grate product!",
    },
  ],
};

export default Data;
